### ISSUE TITLE
Plugin does not work with Vagrant 1.8.1

### ISSUE THREAD

**Issue by tal5ab** [clintoncwolfe/vagrant-rspec-ci#3]
After installing the plugin , any vagrant run result with this error:
```
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub rspec` to work around a system/bundle conflict.
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub rspec` to work around a system/bundle conflict.
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub rspec` to work around a system/bundle conflict.
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub rspec` to work around a system/bundle conflict.
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub rspec` to work around a system/bundle conflict.
C:/Users/cuser.ADPROD/.vagrant.d/gems/gems/vagrant-rspec-ci-1.1.0/lib/vagrant-rspec-ci/config.rb:54:in `validate': undefined method `push' for nil:NilClass (NoMethodError)
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:68:in `block in validate'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:64:in `each'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:64:in `validate'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
                from C:/Users/cuser.ADPROD/.vagrant.d/gems/gems/vagrant-aws-0.7.0/lib/vagrant-aws/provider.rb:32:in `state'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:501:in `state'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `call'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `each'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:89:in `block in execute'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:278:in `block (2 levels) in batch'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:276:in `tap'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:276:in `block in batch'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:275:in `synchronize'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:275:in `batch'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:88:in `execute'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
                from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'

```

**Comment by clintoncwolfe** [comment]
Turned out the incompatibility was with rspec and ci-reporter - either way, a freshening was needed.   Fixed on #4, and released a new gem, version 1.1.1 .

**Comment by tal5ab** [comment]
Hi
I am still getting this issue
Even with Vagrant 1.7.4 , and without any line changed in vagrantfile after installing the plugin again:

INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x3d36e60>
C:/Users/cuser.ADPROD/.vagrant.d/gems/gems/vagrant-rspec-ci-1.1.1/lib/vagrant-rspec-ci/config.rb:58:in `validate': undefined method `push' for nil:NilClass (NoMethodError)
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/root.rb:68:in `block in validate'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/root.rb:64:in `each'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/root.rb:64:in `validate'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from C:/Users/cuser.ADPROD/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/provider.rb:32:in `state'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:490:in `state'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:141:in `initialize'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:79:in `new'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:79:in `machine'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:612:in `machine'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:192:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:174:in `each'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:74:in `block in execute'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `tap'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `block in batch'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `synchronize'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `batch'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:58:in `execute'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
Deploy step failed to run.








C:\>vagrant plugin install vagrant-rspec-ci
Installing the 'vagrant-rspec-ci' plugin. This can take a few minutes...
Installed the plugin 'vagrant-rspec-ci (1.1.1)'!

C:\>vagrant plugin list
winrm-fs (0.2.2)
  - Version Constraint: 0.2.2
vagrant-aws (0.6.0)
  - Version Constraint: 0.6.0
vagrant-awsinfo (0.0.8)
vagrant-rspec-ci (1.1.1)
vagrant-share (1.1.5, system)
vagrant-winrm-syncedfolders (1.0.0)

C:\>vagrant --version
Vagrant 1.7.4

C:\>vagrant plugin uninstall vagrant-rspec-ci
Uninstalling the 'vagrant-rspec-ci' plugin...

C:\>vagrant plugin list
winrm-fs (0.2.2)
  - Version Constraint: 0.2.2
vagrant-aws (0.6.0)
  - Version Constraint: 0.6.0
vagrant-awsinfo (0.0.8)
vagrant-share (1.1.5, system)
vagrant-winrm-syncedfolders (1.0.0)

C:\>vagrant plugin install vagrant-rspec-ci -v 1.0.0
Vagrant 1.7.4

C:\>vagrant gem install vagrant-rspec-ci -v 1.0.0
Vagrant 1.7.4

**Comment by tal5ab** [comment]
Am i missing something?
What need to be installed on the host machine other then this plugin and Vagrant? I tried installing the rspec gem , and got the same result
Does rspec and ruby have to be installed on the new VM ?
I can really use some help here

**Comment by tal5ab** [comment]
Ok
i figured it out
Your plugin cannot locate a test folder , and therefore fails
When i created a spec folder where i run the command , vagrant up is running 

This issue should be reopened:
your plugin is running rspec spec on vagrant up , without anyone tell him to do it (i haven't changed anything on my vagrantfile)
And when it does not find a folder it tries to output an error and fails the vagrant up

**Comment by clintoncwolfe** [comment]
Well, doing some basic tracing, we have your error coming from [here](https://github.com/clintoncwolfe/vagrant-rspec-ci/blob/master/lib/vagrant-rspec-ci/config.rb#L58), which is in an error handler.  You're hitting the error handler because you don't have the right directory structure to use the plugin.

However, the error handler is exploding, because we have a bug: we're not initializing the error list correctly (see [here](https://github.com/clintoncwolfe/vagrant-rspec-ci/blob/master/lib/vagrant-rspec-ci/config.rb#L43).

I'll push a fix here in a few.

**Comment by clintoncwolfe** [comment]
@tal5ab You are of course empowered to open whatever issues you feel are best.  That's how open-source software works.

**Comment by clintoncwolfe** [comment]
I've fixed the error message issue in v1.1.2, now available on rubygems.org .

If you feel this is a problem:

> your plugin is running rspec spec on vagrant up , without anyone tell him to do it (i haven't changed 
> anything on my vagrantfile)

Please open a separate issue, as it is an unrelated behavior change.

**Comment by tal5ab** [comment]
Thank you for such a fast respond and fix
